export const USERS_LOGIN_PENDING = "USERS_LOGIN_PENDING";
export const USERS_LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const USERS_LOGIN_FAILURE = "USERS_LOGIN_FAILURE";

export const SAVE_USER_PENDING = "SAVE_USER_PENDING";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAILURE = "SAVE_USER_FAILURE";

export const FETCH_USER_PENDING = "USERS_FETCH_PENDING";
export const FETCH_USER_SUCCESS = "USERS_FETCH_SUCCESS";
export const FETCH_USER_FAILURE = "USERS_FETCH_FAILURE";

export const FETCH_POSTS_PENDING = "FETCH_POSTS_PENDING";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

export const SAVE_POST_PENDING = "SAVE_POST_PENDING";
export const SAVE_POST_SUCCESS = "SAVE_POST_SUCCESS";
export const SAVE_POST_FAILURE = "SAVE_POST_FAILURE";
