language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

os: linux
branches:
  only:
    - master
    - /^release-\d+\.\d+\.\d+\
    
git:
  depth: 1
  quiet: true


before_script:
  - composer install
